name: chnsmile_flutter
description: A new flutter module project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#
# This version is used _only_ for the Runner app, which is used if you just do
# a `flutter run` or a `flutter make-host-app-editable`. It has no impact
# on any other native host app that you embed your Flutter project into.
version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  hi_base:
    path: ./component/hi_base
  hi_cache:
    path: ./component/hi_cache

  badges: ^2.0.2
  fluttertoast: ^8.0.8
  flutter_swiper: ^1.1.6
  flutter_nested: ^1.0.0
  lottie: ^1.2.1
  path_drawing: ^1.0.0
  audioplayers: 0.20.0
  underline_indicator: ^0.0.4
  dio: ^4.0.5-beta1
  flutter_html: 3.0.0-alpha.5
  flutter_easyloading: ^3.0.3
  ele_progress: ^0.0.1
  flutter_image_compress: ^1.1.0
  file_picker: ^4.3.3
  flutter_plugin_record: ^1.0.1
#  flutter_sound: 8.5.0
#  flutter_sound:
#    path: ./flutter_sound
  path_provider: ^2.0.9
  path: ^1.8.0
  event_bus: ^2.0.0
  logger: ^1.0.0
  meta: ^1.3.0
  provider: ^6.0.0
  recase: ^4.0.0

  flutter_boost:
    git:
      url: 'https://github.com/alibaba/flutter_boost.git'
      ref: 'v3.0-preview.18'

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_color_plugin: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  mockito: ^5.0.0
  pedantic: ^1.11.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    #加载目录下的所有文件
    - images/
    - assets/

  fonts:
    - family: SimSum
      fonts:
        - asset: assets/fonts/SimSum.ttf


  # This section identifies your Flutter project as a module meant for
  # embedding in a native host app.  These identifiers should _not_ ordinarily
  # be changed after generation - they are used to ensure that the tooling can
  # maintain consistency when adding or modifying assets and plugins.
  # They also do not have any bearing on your native host application's
  # identifiers, which may be completely independent or the same as these.
  module:
    androidX: true
    androidPackage: com.example.chnsmile_flutter
    iosBundleIdentifier: com.example.chnsmileFlutter
